site_name: Buildblog
theme:
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  features:
    - navigation.indexes

plugins:
  - search
  - blog

nav:
  - Home: index.md
  - Blog:
     - blog/index.md
    
markdown_extensions:
  - attr_list
  - md_in_html